name: Comment

on:
  pull_request:

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-20.04
    steps:
      - uses: zendesk/github-script@v6
        name: Create status
        with:
          script: |
            // Mark previous comments as outdated by minimizing them.
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: context.issue.number,
            });
            for (const comment of comments) {
              if (comment.user.login === 'github-actions[bot]' && comment.body.includes('test comment')) {
                await github.graphql(`
                  mutation {
                    minimizeComment(input: {subjectId: "${comment.node_id}", classifier: OUTDATED}) {
                      clientMutationId
                    }
                  }
                `);
              }
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `A test comment`
            })
